### ISSUE TITLE
兄弟这个现在是只能看不能用吗？

### ISSUE THREAD

**Issue by yiyayamaya** [imcjx/chat-room#1]
为什么我点create group没用啊

**Comment by imcjx** [comment]
...还没做完 界面都没写完 交互更没做了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yiyayamaya"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 中午1:37
收件人:&nbsp;"imcjx/chat-room"<chat-room@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[imcjx/chat-room] 兄弟这个现在是只能看不能用吗？ (#1)





 
为什么我点create group没用啊
